% clear all
% close all
% 
% % Figure des boutons de Lancement des scripts
% 
% fig = figure('Units','normalized','Position',[0.33 0.33 0.4 0.35],...
%     'NumberTitle','off','Name','Lancement Analyse Fichiers Alcolac','MenuBar','none');
% 
% % Bouton du lancement : Comportemental
% 
% but= uicontrol('Units','normalized','Position',[0.25 0.65 0.2 0.1],...
%     'BackgroundColor',[1 1 0],...
%     'String','Groupe 18 Comp','Callback','Traitement_Comportemental_Alcolac;',...
%     'Style','pushbutton','Value',1);
% but2= uicontrol('Units','normalized','Position',[0.55 0.65 0.2 0.1],...
%     'BackgroundColor',[0 1 0],...
%     'String','Groupe 21 Comp','Callback','Traitement_Comportemental_Alcolac;',...
%     'Style','pushbutton','Value',2);
% butbis = uicontrol('Units','normalized','Position',[0.25 0.80 0.5 0.1],...
%     'BackgroundColor',[0.3 0.6 1],...
%     'String','Données Comportementales',...
%     'Style','text');
% 
% % Bouton du lancement : Physio
% 
% 
% but3= uicontrol('Units','normalized','Position',[0.25 0.25 0.2 0.1],...
%     'BackgroundColor',[1 1 0],...
%     'String','Groupe 18 Phy','Callback','Traitement_Physio_Alcolac_V2;',...
%     'Style','pushbutton','Value',1);
% but4= uicontrol('Units','normalized','Position',[0.55 0.25 0.2 0.1],...
%     'BackgroundColor',[0 1 0],...
%     'String','Groupe 21 Phy','Callback','Traitement_Physio_Alcolac_V2;',...
%     'Style','pushbutton','Value',2);
% buttris = uicontrol('Units','normalized','Position',[0.25 0.40 0.5 0.1],...
%     'BackgroundColor',[0.3 0.6 1],...
%     'String','Données Physiologiques',...
%     'Style','text');