%folder_list = {     'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S010\ALLER'};
% folder_list = {     'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S001\ALLER',...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S001\RETOUR',...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S002\ALLER', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S002\RETOUR', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S003\ALLER', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S003\RETOUR',...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S004\ALLER', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S004\RETOUR',...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S006\ALLER', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S006\RETOUR', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S007\ALLER', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S007\RETOUR',...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S008\ALLER', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S008\RETOUR', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S009\ALLER', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S009\RETOUR', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S010\ALLER', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S010\RETOUR', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S011\ALLER', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S011\RETOUR', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S012\ALLER', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S012\RETOUR', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S013\ALLER', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S013\RETOUR' ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S014\ALLER', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S014\RETOUR',...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S015\ALLER', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S015\RETOUR', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S016\ALLER', ...
%                      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S016\RETOUR'};
                 

folder_list = {      'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S001\ALLER',...
                     'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S001\RETOUR',...
                     'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S002\ALLER', ...
                     'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S002\RETOUR', ...
                     'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S003\ALLER', ...
                     'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S003\RETOUR',...
                     'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S004\ALLER', ...
                     'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S004\RETOUR',...
                     'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S006\ALLER', ...
                     'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S006\RETOUR', ...
                     'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S007\ALLER', ...
                     'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S007\RETOUR'...    
};

    for i = 1:length(folder_list)

        
        files_list = dir(folder_list{i}); 
        
        for ii=1:1:length(files_list)
            if ~files_list(ii).isdir            
                file_path =fullfile(folder_list{i},files_list(ii).name);
                [~,file_name,file_ext]=fileparts(file_path);
                if strcmp(file_ext,'.trip')
                    trip_file= file_path;
                    trip_name = file_name;
                end
                if strcmp(file_ext,'.mat')&& ~isempty(strfind(file_name,'atlas_structure'))
                    mat_file= file_path;
                    mat_name = file_name;
                end
                
            end        
        end
        
        disp(['Le trip ' trip_name ' est en cours de traitement ...']);
        
        trip = fr.lescot.bind.kernel.implementation.SQLiteTrip(trip_file, 0.04, true);
        try
        metas = trip.getMetaInformations;
        record_situation = trip.getAllSituationOccurences('double tache');
        Start_End_timecode = cell2mat(record_situation.buildCellArrayWithVariables({'startTimecode','endTimecode'}));
        
        fh =figure('Name',trip_name);
                
        N=size(Start_End_timecode,2);
        
        for i_situation=1:1:N
           record = trip.getDataOccurencesInTimeInterval('Mopad_SensorsMeasures',Start_End_timecode(1,i_situation),Start_End_timecode(2,i_situation));
            
           timecode = cell2mat(record.getVariableValues('timecode'))/60;
           MindWander = abs(cell2mat(record.getVariableValues('ContactMindWandering')));
           
            
            my_subplot  = subplot(N,1,i_situation);
            
            plot(timecode,MindWander);
            set(my_subplot, 'YLim', [-0.5 10.5])
            set(my_subplot,'XTick',[floor(timecode(1)):1:ceil(timecode(end))])
            ylabel(['Situation ' num2str(i_situation) ]);          
            
        end
        
        print(fh, '-r600', '-djpeg',[trip_name '_Plot_MindWandering'])
        hgsave(fh,[trip_name '_Plot_MindWandering'])
        catch
        end
        
        
    end