% This script is used to integrate the MinWandering declaration data included in the trip to
% Continental structure

function TripMW2struct()

%    folder_list = {'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S003\ALLER', ...
%                    'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S014\ALLER', ...
%                    'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S014\RETOUR'};
               
folder_list = {  'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S001\ALLER',...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S001\RETOUR',...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S002\ALLER', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S002\RETOUR', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S003\ALLER', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S003\RETOUR',...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S004\ALLER', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S004\RETOUR',...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S005\ALLER', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S005\RETOUR', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S006\ALLER', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S006\RETOUR', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S007\ALLER', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S007\RETOUR',...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S008\ALLER', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S008\RETOUR', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S009\ALLER', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S009\RETOUR', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S010\ALLER', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S010\RETOUR', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S011\ALLER', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S011\RETOUR', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S012\ALLER', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S012\RETOUR', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S013\ALLER', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S013\RETOUR', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S014\ALLER', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S014\RETOUR',...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S015\ALLER', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S015\RETOUR', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S016\ALLER', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S016\RETOUR', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S017\ALLER', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S017\RETOUR', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S018\ALLER', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S018\RETOUR', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S019\ALLER', ...
                 'D:\LESCOT\PROJETS\ATLAS\Atlas Route\DONNEES\MANIPS\S019\RETOUR'};
                
    for i = 1:1:length(folder_list)
   
        files_list = dir(folder_list{i}); 
        
        for ii=1:1:length(files_list)
            if ~files_list(ii).isdir            
                file_path =fullfile(folder_list{i},files_list(ii).name);
                [~,file_name,file_ext]=fileparts(file_path);
                if strcmp(file_ext,'.trip')
                    trip_file= file_path;
                    trip_name = file_name;
                end
                if strcmp(file_ext,'.mat')&& ~isempty(strfind(file_name,'atlas_structure'))
                    mat_file= file_path;
                    mat_name = file_name;
                end
                
            end        
        end
        
        disp(['Le trip ' trip_name ' est en cours de traitement ...']);
        
        trip = fr.lescot.bind.kernel.implementation.SQLiteTrip(trip_file, 0.04, true);
        %%Trip processing
        
        record_SynchroVideo = trip.getAllDataOccurences('mopad_Synchrovideo');
        
        timecode = cell2mat( record_SynchroVideo.getVariableValues('timecode'));
        
        
        recordMW = trip.getAllEventOccurences('MindWandering');
        declarationMW = cell2mat(recordMW.getVariableValues('timecode'));

        declarationMW_continu = zeros(size(timecode));
        
        for i_declar =1:1:length(declarationMW)
        declarationMW_continu(timecode == declarationMW(i_declar)) =1;
        end
        
        load(mat_file);
        
        name = fieldnames(atlas);
        atlas.(name{1}).mopad.Synchrovideo.MindWAndering.values = declarationMW_continu;
        atlas.(name{1}).mopad.Synchrovideo.MindWAndering.unit = 'no unit';
        atlas.(name{1}).mopad.Synchrovideo.MindWAndering.comments = 'this data contains the participant autodeclaration of MindWandering';
        
        save(mat_file,'atlas');
        
        delete(trip)
        
        %% Cardiaque data Processing
 
        
        
        
    end
end