%% import_kvaser_struct
% This function loads a kvaser file (exported in matlab format), parse the
% variables to construct a Matlab structure that can be shared with other
% people. The structure has been defined in the Safemove project. It can be
% reused in any project.
% 
% Remarks: The function hard codes the way the structure will
% be defined. If you want to filter some of the variables, comment the
% appropriate lines in the function.
%
% input argument:
% kvaser_file_name: name of the kvaser file exported in matlab format.
%
% output argument:
% kvaser:           a structure containing the relevant CAN data.

function kvaser = import_kvaser_struct(kvaser_file_name)

    kvaser_struct = load(kvaser_file_name);
    kvaser = struct;

    names = fieldnames(kvaser_struct);
    num_var = length(names);
    for i = 1:num_var
        % load the current variable in "kvaser_variable"
        kvaser_variable = getfield(kvaser_struct,names{i});    
        % prepare an empty struct that will contain the new variable
        new_variable = struct;

        % suppression des suffixes '_01' .. '1N'
        nameVar=names;
        for j=2:num_var
        S=nameVar{j};
            if strcmp(S(end-2),'_')
            S = S(1:end-3);
            end
        nameVar{j}=S;
        end
        
        switch names{i}
            % meta infos du header
            case 'header'
                % on recopie la sous-structure header directement
                new_variable = kvaser_variable;
                kvaser = setfield(kvaser,'META',new_variable);
               
            % Gestion des infos ALDW
            case { ...
                    ... % CAN4_LO
                    'LDW3_12_ALDW_BrkOrient_Id_00', ...
                    'LDW3_12_ALDW_IndLmp_On_Rq_01', ...
                    'LDW3_12_ALDW_LanMk_DtctDist_04', ...
                    'LDW3_12_ALDW_LanMkLftWidth_02', ...
                    'LDW3_12_ALDW_LanMkRitWidth_03', ...
                    'LDW3_12_ALDW_MsgDisp_Rq_05', ...
                    'LDW3_12_ALDW_OnCal_Stat_07', ...
                    'LDW3_12_ALDW_OnCalExecDist_06', ...
                    'LDW3_12_ALDW_VibTm_Rq_08', ...
                    'LDW3_12_ALDW_Warn_Rq_09', ...
                    ... % Lescot_CAN4_V1_1
                    'ALDW_A1_00_ALDW_BrkOrient_Id_00', ...
                    'ALDW_A1_00_ALDW_ImgSyncNumbe_01', ...
                    'ALDW_A1_00_ALDW_IndLmp_On_Rq_02', ...
                    'ALDW_A1_00_ALDW_LaneMark_Dtc_05', ...
                    'ALDW_A1_00_ALDW_LaneMarkWidt_03', ...
                    'ALDW_A1_00_ALDW_LaneMarkWidt_04', ...
                    'ALDW_A1_00_ALDW_Menu_Enbl_Rq_06', ...
                    'ALDW_A1_00_ALDW_MsgDisp_Rq_07', ...
                    'ALDW_A1_00_ALDW_OnCal_Stat_09', ...
                    'ALDW_A1_00_ALDW_OnCalExecDis_08', ...
                    'ALDW_A1_00_ALDW_VibTm_Rq_10', ...
                    'ALDW_A1_00_ALDW_Warn_Rq_11', ...
                    'ALDW_A1_00_CRC_ALDW_A1_12', ...
                    'ALDW_A1_00_MC_ALDW_A1_13'}
%                 kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,'ALDW_00',names{i},kvaser); 
                
                groupVar=strtok(names,'_');
                
                nameVar=strrep(nameVar,'LDW3_12_','');  
                kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,groupVar{i},nameVar{i},kvaser); 

                case { ...
                    ... % CAN4_LO
                    'LDW1_10_ALDW_LaneChg_Stat_00', ...
                    'LDW1_10_ALDW_LaneDataQual_01', ...
                    'LDW1_10_ALDW_LaneLtrlDist_02', ...
                    'LDW1_10_ALDW_LaneNum_03', ...
                    'LDW1_10_ALDW_LaneTrckTm_04', ...
                    'LDW1_10_ALDW_LaneWidth_05', ...
                    'LDW1_10_ALDW_LaneYawAngl_06', ...
                    'LDW1_10_ALDW_NumLane_07', ...
                    'LDW1_10_ALDW_RoadExit_Stat_08', ...
                    'LDW1_10_ALDW_RoadType_09', ...
                    ... % Lescot_CAN4_V1_1
                    'ALDW_LANE1_01_ALDW_LaneChg_S_00', ...
                    'ALDW_LANE1_01_ALDW_LaneDataQ_01', ...
                    'ALDW_LANE1_01_ALDW_LaneLtrlD_02', ...
                    'ALDW_LANE1_01_ALDW_LaneNum_03', ...
                    'ALDW_LANE1_01_ALDW_LaneTrckT_04', ...
                    'ALDW_LANE1_01_ALDW_LaneWidth_05', ...
                    'ALDW_LANE1_01_ALDW_LaneYawAn_06', ...
                    'ALDW_LANE1_01_ALDW_NumLane_07', ...
                    'ALDW_LANE1_01_ALDW_RoadExit__08', ...
                    'ALDW_LANE1_01_ALDW_RoadType_09', ...
                    'ALDW_LANE1_01_CRC_ALDW_LANE1_10', ...
                    'ALDW_LANE1_01_MC_ALDW_LANE1_11' ...
                    }
%                 kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,'ALDW_01',names{i},kvaser);  
                
                groupVar=strtok(names,'_');
                
                nameVar=strrep(nameVar,'LDW1_10_','');  
                kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,groupVar{i},nameVar{i},kvaser); 
            case {  ...
                    ... % CAN4_LO
                    'LDW2_11_ALDW_LanClothoidPara_00', ...
                    'LDW2_11_ALDW_LaneHrztCrv_08', ...
                    'LDW2_11_ALDW_LanMk_Lt_Stat_05', ...
                    'LDW2_11_ALDW_LanMk_Rt_Stat_06', ...
                    'LDW2_11_ALDW_LanMkCol_Lt_01', ...
                    'LDW2_11_ALDW_LanMkCol_Rt_02', ...
                    'LDW2_11_ALDW_LanMkLftType_03', ...
                    'LDW2_11_ALDW_LanMkRitType_04', ...
                    'LDW2_11_ALDW_LanSitDtct_Stat_07', ...
                    'LDW2_11_ALDW_VehPitchAngl_09', ...
                    ... % Lescot_CAN4_V1_1
                    'ALDW_LANE2_02_ALDW_LaneCloth_00', ...
                    'ALDW_LANE2_02_ALDW_LaneHrztC_01', ...
                    'ALDW_LANE2_02_ALDW_LaneMark__06', ...
                    'ALDW_LANE2_02_ALDW_LaneMark__07', ...
                    'ALDW_LANE2_02_ALDW_LaneMarkC_02', ...
                    'ALDW_LANE2_02_ALDW_LaneMarkC_03', ...
                    'ALDW_LANE2_02_ALDW_LaneMarkT_04', ...
                    'ALDW_LANE2_02_ALDW_LaneMarkT_05', ...
                    'ALDW_LANE2_02_ALDW_LaneSiteD_08', ...
                    'ALDW_LANE2_02_ALDW_VehPitchA_09', ...
                    'ALDW_LANE2_02_CRC_ALDW_LANE2_10', ...
                    'ALDW_LANE2_02_MC_ALDW_LANE2_11' ...
                    }
%                 kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,'ALDW_02',names{i},kvaser);   

                groupVar=strtok(names,'_');
                
                nameVar=strrep(nameVar,'LDW2_11_','');  
                kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,groupVar{i},nameVar{i},kvaser); 
            
            case {  ...
                    ... % CAN4_LO
                    'ARSSt_04_NumOfObjects_00', ...
                    ... % Lescot_CAN4_V1_1
                    'ARS_Stat_05_InterfaceVersion_00' , ...
                    'ARS_Stat_05_MeasCounter_01' , ...
                    'ARS_Stat_05_NumOfObjects_02' ...
                    }
%                 kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,'ARS_Stat',names{i},kvaser); 
                
                groupVar=strtok(names,'_');
                
                nameVar=strrep(nameVar,'ARSSt_04_','');  
                kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,groupVar{i},nameVar{i},kvaser); 
            
            case {  ...
                    ... % CAN4_LO
                    'ARS1_02_Obj_AccelLong_00', ...
                    'ARS1_02_Obj_DynProp_01', ...
                    'ARS1_02_Obj_ID_02', ...
                    'ARS1_02_Obj_LatDispl_03', ...
                    'ARS1_02_Obj_Length_04', ...
                    'ARS1_02_Obj_LongDispl_05', ...
                    'ARS1_02_Obj_MeasStat_06', ...
                    'ARS1_02_Obj_ProbOfExist_07', ...
                    'ARS1_02_Obj_RollCount_08', ...
                    'ARS1_02_Obj_VrelLong_09', ...
                    'ARS1_02_Obj_Width_10', ...
                    ... % Lescot_CAN4_V1_1
                    'ARS1_03_Obj_AccelLong_00' , ...
                    'ARS1_03_Obj_DynProp_01' , ...
                    'ARS1_03_Obj_ID_02' , ...
                    'ARS1_03_Obj_LatDispl_03' , ...
                    'ARS1_03_Obj_Length_04' , ...
                    'ARS1_03_Obj_LongDispl_05' , ...
                    'ARS1_03_Obj_MeasStat_06' , ...
                    'ARS1_03_Obj_ProbOfExist_07' , ...
                    'ARS1_03_Obj_RollCount_08' , ...
                    'ARS1_03_Obj_VrelLong_09' , ...
                    'ARS1_03_Obj_Width_10' ...
                    }
%                 kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,'ARS1',names{i},kvaser);   
                
                groupVar=strtok(names,'_');
                
                nameVar=strrep(nameVar,'ARS1_02_','');
                kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,groupVar{i},nameVar{i},kvaser); 
            
            case {  ...
                    ... % CAN4_LO
                    'ARS2_03_Obj_LatSpeed_00', ...
                    'ARS2_03_Obj_ObstacleProba_01', ...
                    'ARS2_03_Obj_RCSValue_02', ...
                    ... % Lescot_CAN4_V1_1
                    'ARS2_04_Obj_LatSpeed_00' , ...
                    'ARS2_04_Obj_ObstacleProbabil_01' , ...
                    'ARS2_04_Obj_RCSValue_02' ...
                    }
%                 kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,'ARS2',names{i},kvaser);  
                
                groupVar=strtok(names,'_');
                
                nameVar=strrep(nameVar,'ARS2_03_','');  
                kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,groupVar{i},nameVar{i},kvaser); 

            case {  ...
                    ... % Lescot_CAN4_V1_1
                    'IS_DAT_ABR_5_06_ALRT_LIQU_FR_00' , ...
                    'IS_DAT_ABR_5_06_CPT_TOP_ARD_01' , ...
                    'IS_DAT_ABR_5_06_CPT_TOP_ARG_02' , ...
                    'IS_DAT_ABR_5_06_DEFAUT_ABR_03' , ...
                    'IS_DAT_ABR_5_06_DEFAUT_CMPT__04' , ...
                    'IS_DAT_ABR_5_06_DEFAUT_CMPT__05' , ...
                    'IS_DAT_ABR_5_06_FNCT_AAFD_UC_06' , ...
                    'IS_DAT_ABR_5_06_REGUL_ABR_07' , ...
                    'IS_DAT_ABR_5_06_REGUL_REF_08' , ...
                    'IS_DAT_ABR_5_06_REQ_LAMPE_DE_09' , ...
                    'IS_DAT_ABR_5_06_REQ_LAMPE_DE_10' , ...
                    'IS_DAT_ABR_5_06_USURE_PLAQ_F_11' ...
                    }
                kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,'IS_DAT_ABR',names{i},kvaser);  

            case {  ...
                    ... % CAN4_LO
                    'ACCEL_01_ACCEL_LAT_BRUTE_RB_00', ...
                    'ACCEL_01_VIT_LACET_BRUTE_RB_01', ...
                    ... % Lescot_CAN4_V1_1
                    'IS_DAT_ACCEL_07_ACCEL_LAT_BR_00' , ...
                    'IS_DAT_ACCEL_07_BIT_CALIB__R_01' , ...
                    'IS_DAT_ACCEL_07_BIT_ERR_RB_02' , ...
                    'IS_DAT_ACCEL_07_BIT_ERR_SUSP_03' , ...
                    'IS_DAT_ACCEL_07_BIT_ERR_TMPO_04' , ...
                    'IS_DAT_ACCEL_07_BIT_MODE_TES_05' , ...
                    'IS_DAT_ACCEL_07_INFO_INTERNE_06' , ...
                    'IS_DAT_ACCEL_07_NUM_ERR_RB_07' , ...
                    'IS_DAT_ACCEL_07_OCTET_IDENT__08' , ...
                    'IS_DAT_ACCEL_07_POS_BIT_BIT__09' , ...
                    'IS_DAT_ACCEL_07_VITESSE_LACE_10' ...
                    }
%                 kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,'IS_DAT_ACCEL',names{i},kvaser); 
                
                groupVar=strtok(names,'_');
                
                nameVar=strrep(nameVar,'ACCEL_01_','');  
                kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,groupVar{i},nameVar{i},kvaser); 

            case {  ...
                    ... % CAN4_LO <- ATTENTION, pas de CONTACT_FREIN1
                    'BSI_05_CONTACT_FREIN_PRK_00', ...
                    'BSI_05_ETAT_FEUX_CROIST_01', ...
                    'BSI_05_MARCHE_AR_BVM_02', ...
                    ... % CAN4_LOpti_V2
                    'BSI_05_CONTACT_FREIN_PRK_01', ...
                    'BSI_05_CONTACT_FREIN1_00', ...
                    'BSI_05_ETAT_FEUX_CROIST_02', ...
                    'BSI_05_MARCHE_AR_BVM_03', ...
                    ... % Lescot_CAN4_V1_1
                    'IS_DAT_BSI_4_08_ACTIVATION_H_00' , ...
                    'IS_DAT_BSI_4_08_AUTOR_BSI_DA_01' , ...
                    'IS_DAT_BSI_4_08_CDES_RVV_02' , ...
                    'IS_DAT_BSI_4_08_CONTACT_FREI_05' , ...
                    'IS_DAT_BSI_4_08_CONTACT_FREI_03' , ...
                    'IS_DAT_BSI_4_08_CONTACT_FREI_04' , ...
                    'IS_DAT_BSI_4_08_D_LIGNE_REL__14' , ...
                    'IS_DAT_BSI_4_08_DDE_CHAUF_HA_06' , ...
                    'IS_DAT_BSI_4_08_DDE_MES_HUIL_07' , ...
                    'IS_DAT_BSI_4_08_DDE_SPORTIVI_08' , ...
                    'IS_DAT_BSI_4_08_DEFAUT_BES_H_09' , ...
                    'IS_DAT_BSI_4_08_DEFAUT_BES_S_10' , ...
                    'IS_DAT_BSI_4_08_DIAG_MINI_CA_11' , ...
                    'IS_DAT_BSI_4_08_DMD_CLIGNOTA_12' , ...
                    'IS_DAT_BSI_4_08_DMD_CLIGNOTA_13' , ...
                    'IS_DAT_BSI_4_08_ETAT_FEUX_CR_15' , ...
                    'IS_DAT_BSI_4_08_ETAT_LNTT_AR_16' , ...
                    'IS_DAT_BSI_4_08_ETAT_OUVRANT_17' , ...
                    'IS_DAT_BSI_4_08_ETAT_POMPE_A_18' , ...
                    'IS_DAT_BSI_4_08_ETAT_POMPE_E_19' , ...
                    'IS_DAT_BSI_4_08_ETAT_TOIT_OU_20' , ...
                    'IS_DAT_BSI_4_08_MARCHE_AR_BV_21' , ...
                    'IS_DAT_BSI_4_08_MINI_CARB_22' , ...
                    'IS_DAT_BSI_4_08_NIV_MIN_ADDI_23' , ...
                    'IS_DAT_BSI_4_08_PBE_ON_24' , ...
                    'IS_DAT_BSI_4_08_PLUS_APC_25' , ...
                    'IS_DAT_BSI_4_08_PLUS_DEM_26' , ...
                    'IS_DAT_BSI_4_08_PUSH_1ERE_BV_27' , ...
                    'IS_DAT_BSI_4_08_PUSH_BV_NEIG_28' , ...
                    'IS_DAT_BSI_4_08_PUSH_BV_SPOR_29' , ...
                    'IS_DAT_BSI_4_08_PUSH_COFFRE__30' , ...
                    'IS_DAT_BSI_4_08_PUSH_COFFRE__31' , ...
                    'IS_DAT_BSI_4_08_PUSH_HAUT_MO_32' , ...
                    'IS_DAT_BSI_4_08_PUSH_HAUT_PL_33' , ...
                    'IS_DAT_BSI_4_08_PUSH_SUSP_AP_34' , ...
                    'IS_DAT_BSI_4_08_REQ_CHAUF_HA_35' , ...
                    'IS_DAT_BSI_4_08_REQ_DECON_AS_36' , ...
                    'IS_DAT_BSI_4_08_RVV_ON_37' , ...
                    'IS_DAT_BSI_4_08_TEMP_AVAL_FA_38' , ...
                    'IS_DAT_BSI_4_08_TEMP_HUILE_M_39' ...
                    }
%                 kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,'IS_DAT_BSI',names{i},kvaser);  

                groupVar=strtok(names,'_');
                
                nameVar=strrep(nameVar,'BSI_05_','');  
                kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,groupVar{i},nameVar{i},kvaser);


            case {  ...
                    ... % CAN4_LO
                    'CLIM_06_CONS_LIM_VITESSE_VEH_00', ...
                    'CLIM_06_DDE_ACTIVATION_LVV_01', ...
                    'CLIM_06_DDE_ACTIV_RVV_ACC_02', ...
                    'CLIM_06_TYPE_REGUL_LONGI_03', ...
                    ...% Lescot_CAN4_V1_1
                    'IS_DAT_CLIM__09_AC_TH_00' , ...
                    'IS_DAT_CLIM__09_APPUI_PUSH_G_01' , ...
                    'IS_DAT_CLIM__09_AUTOR_ARRET__02' , ...
                    'IS_DAT_CLIM__09_BES_SE_STT_03' , ...
                    'IS_DAT_CLIM__09_CHKSUM_CONS__04' , ...
                    'IS_DAT_CLIM__09_CNS_CONT_GMV_05' , ...
                    'IS_DAT_CLIM__09_CONS_LIM_VIT_07' , ...
                    'IS_DAT_CLIM__09_CONSIGNE_GMV_06' , ...
                    'IS_DAT_CLIM__09_CONT_EMBR_BS_08' , ...
                    'IS_DAT_CLIM__09_CPT_TRAME_BS_09' , ...
                    'IS_DAT_CLIM__09_DDE_ACTIVATI_10' , ...
                    'IS_DAT_CLIM__09_DDE_ACTIVATI_11' , ...
                    'IS_DAT_CLIM__09_DDE_DEBIT_AE_12' , ...
                    'IS_DAT_CLIM__09_DDE_HABITACL_13' , ...
                    'IS_DAT_CLIM__09_DDE_REDEM_HA_14' , ...
                    'IS_DAT_CLIM__09_DDE_REDEM_MO_15' , ...
                    'IS_DAT_CLIM__09_DEF_IDENT_HA_16' , ...
                    'IS_DAT_CLIM__09_DEM_RAL_HAB_17' , ...
                    'IS_DAT_CLIM__09_DIAG_MINI_GP_18' , ...
                    'IS_DAT_CLIM__09_ETAT_EMB_COM_19' , ...
                    'IS_DAT_CLIM__09_ETAT_RELAIS__20' , ...
                    'IS_DAT_CLIM__09_FORCAGE_ENCL_21' , ...
                    'IS_DAT_CLIM__09_FORCAGE_ENCL_22' , ...
                    'IS_DAT_CLIM__09_IND_PRESENCE_23' , ...
                    'IS_DAT_CLIM__09_INTERD_ARRET_24' , ...
                    'IS_DAT_CLIM__09_MINI_GPL_25' , ...
                    'IS_DAT_CLIM__09_NIV_DELESTAG_26' , ...
                    'IS_DAT_CLIM__09_PRES_COND_27' , ...
                    'IS_DAT_CLIM__09_PUISS_MECA_C_28' , ...
                    'IS_DAT_CLIM__09_SATURATION_A_29' , ...
                    'IS_DAT_CLIM__09_TYPE_REGUL_L_30' ...
                    }
%                 kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,'IS_DAT_CLIM',names{i},kvaser); 

                groupVar=strtok(names,'_');
                
                nameVar=strrep(nameVar,'CLIM_06_',''); 
                kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,groupVar{i},nameVar{i},kvaser);

            case {  ...
                    ... % CAN4_LO
                    'CMM4_09_CONSO_CARBURANT_00', ...
                    'CMM4_09_TYPE_CONSO_CARB_01', ...
                    ...% Lescot_CAN4_V1_1
                    'IS_DAT_CMM_4_10_ALERTE_NIV_M_00' , ...
                    'IS_DAT_CMM_4_10_ALRT_TEMP_EA_01' , ...
                    'IS_DAT_CMM_4_10_CNS_POMPE_AI_02' , ...
                    'IS_DAT_CMM_4_10_CNS_POMPE_EA_03' , ...
                    'IS_DAT_CMM_4_10_CNS_REGUL_RA_04' , ...
                    'IS_DAT_CMM_4_10_CONSO_CARBUR_05' , ...
                    'IS_DAT_CMM_4_10_COUP_CLIM_SE_06' , ...
                    'IS_DAT_CMM_4_10_DDE_ALLUM_VO_07' , ...
                    'IS_DAT_CMM_4_10_DEFAUT_RVV_L_08' , ...
                    'IS_DAT_CMM_4_10_DEM_EN_COURS_09' , ...
                    'IS_DAT_CMM_4_10_DMD_REL_PULS_10' , ...
                    'IS_DAT_CMM_4_10_ETAT_GESTION_11' , ...
                    'IS_DAT_CMM_4_10_FORCAGE_PRES_12' , ...
                    'IS_DAT_CMM_4_10_PREPARE_BOUG_13' , ...
                    'IS_DAT_CMM_4_10_PRESSION_REF_14' , ...
                    'IS_DAT_CMM_4_10_RATES_COMBUS_15' , ...
                    'IS_DAT_CMM_4_10_REQ_LAMPE_MI_16' , ...
                    'IS_DAT_CMM_4_10_REQ_LAMPE_PR_17' , ...
                    'IS_DAT_CMM_4_10_RISQUE_COLMA_18' , ...
                    'IS_DAT_CMM_4_10_SEUIL_COUP_S_19' , ...
                    'IS_DAT_CMM_4_10_TEMP_AIR_MOT_20' , ...
                    'IS_DAT_CMM_4_10_TEMP_EAU_MOT_21' , ...
                    'IS_DAT_CMM_4_10_TEMP_HUILE_M_22' , ...
                    'IS_DAT_CMM_4_10_TYPE_INFO_CO_23' ...
                    }
%                 kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,'IS_DAT_CMM',names{i},kvaser); 

                groupVar=strtok(names,'_');
                
                nameVar=strrep(nameVar,'CMM4_09_','');  
                kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,groupVar{i},nameVar{i},kvaser);
            case {  ...
                    ... % CAN4_LO
                    'ABR_00_ACCEL_LONGI_ROUES_00', ...
                    'ABR_00_DISTANCE_ROUES_01', ...
                    'ABR_00_VITESSE_VEH_ROUES_02', ...
                    ...% Lescot_CAN4_V1_1
                    'IS_DYN_ABR_3_12_ACCEL_LONGI__00' , ...
                    'IS_DYN_ABR_3_12_DISTANCE_ROU_01' , ...
                    'IS_DYN_ABR_3_12_VITESSE_VEHI_02' ...
                    }
%                 kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,'IS_DYN_ABR',names{i},kvaser);
                
                groupVar=strtok(names,'_');
                
                nameVar=strrep(nameVar,'ABR_00_','');  
                kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,groupVar{i},nameVar{i},kvaser);

            case {  ...
                    ... % CAN4_LO
                    'CMM2_07_CONTACT_FREIN2_00', ...
                    'CMM2_07_COUPLE_REEL_01', ...
                    'CMM2_07_ETAT_RVV_LVV_02', ...
                    'CMM2_07_REGIME_MOTEUR_03', ...
                    'CMM2_07_VOLONTE_COND_04', ...
                    ... % Lescot_CAN4_V1_1
                    'IS_DYN_CMM_2_13_AC_OUT_00' , ...
                    'IS_DYN_CMM_2_13_CONTACT_FREI_01' , ...
                    'IS_DYN_CMM_2_13_COUPLE_REEL_02' , ...
                    'IS_DYN_CMM_2_13_CPLE_ANTICIP_03' , ...
                    'IS_DYN_CMM_2_13_CPLE_COND_AP_04' , ...
                    'IS_DYN_CMM_2_13_CPLE_MT_INCE_05' , ...
                    'IS_DYN_CMM_2_13_CPLE_REEL_HO_06' , ...
                    'IS_DYN_CMM_2_13_DIAG_MUX_ON_07' , ...
                    'IS_DYN_CMM_2_13_ETAT_RVV_LVV_08' , ...
                    'IS_DYN_CMM_2_13_FIGEAGE_PERT_09' , ...
                    'IS_DYN_CMM_2_13_REGIME_MOTEU_10' , ...
                    'IS_DYN_CMM_2_13_REQ_CHARGE_M_11' , ...
                    'IS_DYN_CMM_2_13_VOLONTE_COND_12' ...
                    }
%                 kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,'IS_DYN_CMM',names{i},kvaser); 

                groupVar=strtok(names,'_');
                
                nameVar=strrep(nameVar,'CMM2_07_','');  
                kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,groupVar{i},nameVar{i},kvaser);

            case {  ...
                    ...% Lescot_CAN4_V1_1
                    'IS_DYN_REQ_B_14_BIT_CALIB__R_00' , ...
                    'IS_DYN_REQ_B_14_BIT_PASSAGE__01' , ...
                    'IS_DYN_REQ_B_14_DEFAUT_CAPT__02' , ...
                    'IS_DYN_REQ_B_14_DEFAUT_CAPT__03' , ...
                    'IS_DYN_REQ_B_14_INFO_INTERNE_04' , ...
                    'IS_DYN_REQ_B_14_OCTET_IDENT__05' ...
                    }
                kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,'IS_DYN_REQ',names{i},kvaser); 
            case {  ...
                    ... % CAN4_LO
                    'VOL_14_ANGLE_VOLANT_00', ...
                    'VOL_14_VITESSE_ROT_VOL_01', ...
                    ...% Lescot_CAN4_V1_1
                    'IS_DYN_VOL_3_15_ANGLE_VOLANT_00' , ...
                    'IS_DYN_VOL_3_15_CALIBRATION__01' , ...
                    'IS_DYN_VOL_3_15_CHKSUM_VOL_02' , ...
                    'IS_DYN_VOL_3_15_CODE_DEFAUT__03' , ...
                    'IS_DYN_VOL_3_15_CPT_PROCESS__04' , ...
                    'IS_DYN_VOL_3_15_ETAT_CAPT_VO_05' , ...
                    'IS_DYN_VOL_3_15_SENS_ROT_VOL_06' , ...
                    'IS_DYN_VOL_3_15_TRIM_VOL_07' , ...
                    'IS_DYN_VOL_3_15_VITESSE_ROT__08' ...
                    }
%                 kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,'IS_DYN_VOL',names{i},kvaser); 
                
                groupVar=strtok(names,'_');
                
                nameVar=strrep(nameVar,'VOL_14_','');
                kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,groupVar{i},nameVar{i},kvaser);
                
            case {  ...
                    ... % CAN4_LO
                    'CMM3_08_CONT_EMBR_CMM_00', ...
                    'CMM3_08_COUPLE_RESISTANT_01', ...
                    'CMM3_08_CPLE_COND_AVT_TRT_02', ...
                    'CMM3_08_RAP_ENGAGE_CALCULE_03', ...
                    ... % Lescot_CAN4_V1_1
                    'IS_DYN2_CMM__11_ACQ_ASR_MSR_00' , ...
                    'IS_DYN2_CMM__11_AUTORIS_DECO_01' , ...
                    'IS_DYN2_CMM__11_BES_PREP_MOT_02' , ...
                    'IS_DYN2_CMM__11_CONS_SOUL_PU_04' , ...
                    'IS_DYN2_CMM__11_CONSIGNE_MV__03' , ...
                    'IS_DYN2_CMM__11_CONT_EMBR_CM_06' , ...
                    'IS_DYN2_CMM__11_CONTACT_OBD_05' , ...
                    'IS_DYN2_CMM__11_COUPLE_RESIS_07' , ...
                    'IS_DYN2_CMM__11_CPLE_COND_AV_08' , ...
                    'IS_DYN2_CMM__11_DDE_MODE_BV__09' , ...
                    'IS_DYN2_CMM__11_DDE_MT_SG_10' , ...
                    'IS_DYN2_CMM__11_DELESTAGE_SE_11' , ...
                    'IS_DYN2_CMM__11_EAU_GAZOLE_12' , ...
                    'IS_DYN2_CMM__11_ETAT_CNS_ASR_13' , ...
                    'IS_DYN2_CMM__11_ETAT_COMBUST_14' , ...
                    'IS_DYN2_CMM__11_ETAT_CONS_AP_15' , ...
                    'IS_DYN2_CMM__11_ETAT_MT_16' , ...
                    'IS_DYN2_CMM__11_ETAT_REALISA_17' , ...
                    'IS_DYN2_CMM__11_MODES_DEGRAD_18' , ...
                    'IS_DYN2_CMM__11_PRES_DEF_OBD_20' , ...
                    'IS_DYN2_CMM__11_PRESSION_REF_19' , ...
                    'IS_DYN2_CMM__11_RAP_ENGAGE_C_21' , ...
                    'IS_DYN2_CMM__11_REQ_MIL_CLNG_22' , ...
                    'IS_DYN2_CMM__11_REQ_MIL_FIXE_23' , ...
                    'IS_DYN2_CMM__11_SOUTIEN_GENE_24' , ...
                    'IS_DYN2_CMM__11_SYNCHRO_DC_G_25' ...
                    }
%                 kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,'IS_DYN2_CMM',names{i},kvaser);

                groupVar=strtok(names,'_');
                
                nameVar=strrep(nameVar,'CMM3_08_','');  
                kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,groupVar{i},nameVar{i},kvaser);

            case {  ...
                    ... % CAN4_LO
                    'VROUES_15_REG_MOY_ROUES_AV_00', ...
                    'VROUES_15_VIT_ROUE_ARD_01', ...
                    'VROUES_15_VIT_ROUE_ARG_02', ...
                    'VROUES_15_VIT_VEH_ROUES_AV_03', ...
                    ... % Lescot_CAN4_V1_1
                    'IS_VROUES_AB_16_REGIME_MOYEN_00' , ...
                    'IS_VROUES_AB_16_VITESSE_ROUE_01' , ...
                    'IS_VROUES_AB_16_VITESSE_ROUE_02' , ...
                    'IS_VROUES_AB_16_VITESSE_VEH__03' , ...
                    }
%                 kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,'IS_DYN',names{i},kvaser); 

                groupVar=strtok(names,'_');
                
                nameVar=strrep(nameVar,'VROUES_15_','');  
                kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,groupVar{i},nameVar{i},kvaser);
            case {  ...
                    ...% Lescot_CAN4_V1_1
                    'RadarState_17_currElevationC_08' , ...
                    'RadarState_17_CurrentRadarPo_00' , ...
                    'RadarState_17_currRangeLengt_09' , ...
                    'RadarState_17_NVMreadStatus_01' , ...
                    'RadarState_17_NVMwriteStatus_02' , ...
                    'RadarState_17_RadarPowerRedu_03' , ...
                    'RadarState_17_RxInvalid_04' , ...
                    'RadarState_17_SensDef_05' , ...
                    'RadarState_17_SensTempErr_06' , ...
                    'RadarState_17_SupVolt_L_07' ...
                    }
                kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,'RadarState',names{i},kvaser); 
            case {  ...
                    ... % CAN4_LO
                    'SLA_13_SLA_WarnSpd_Val_00', ...
                    ... % Lescot_CAN4_V1_1
                    'SLA_DISP_RQ2_18_SLA_SpdWarn__00' , ...
                    'SLA_DISP_RQ2_18_SLA_SpdWarn__01' , ...
                    'SLA_DISP_RQ2_18_SLA_SpdWarn__02' , ...
                    'SLA_DISP_RQ2_18_SLA_WarnSpd__03' , ...
                    'SLA_DISP_RQ2_18_SLA_WarnSpd__04' ...
                    }
%                 kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,'SLA',names{i},kvaser); 
                
                groupVar=strtok(names,'_');
                
                nameVar=strrep(nameVar,'SLA_13_','');  
                kvaser = import_kvaser_variable_in_new_structure(kvaser_variable,groupVar{i},nameVar{i},kvaser);
                
            otherwise
        end
    end
    % free some memory
    clear('kvaser_struct');
end


%% import_kvaser_variable_in_new_structure
% This function is used in import_kvaser_struct
% Given a kvaser structure that contains the description of the variable
% (kvaser_variable), the name of the goup of variable in which this
% variable will be included (group_name), the name of the variable
% (variable_name) and the output_structure that is being created in
% import_kvaser_variable_in_new_structure (new_struct)
%
% remarks: all variables of a same group must have the same timecodes. If
% there are some inconsistencies in the time code, a warning will be
% displayed.

function new_struct = import_kvaser_variable_in_new_structure(kvaser_variable,group_name,variable_name,new_struct)
    % prepare an empty struct that will contain the new variable
    new_variable = struct;
    % test if the ALDW structure already exists in kvaser variable
    if any(strcmp(fieldnames(new_struct),group_name))
        % if it exists...
        % create that the timecodes of the ALDW matches the
        % timecodes of the evaluated structure.
        group_struct = getfield(new_struct,group_name);
        if length(group_struct.time.values) ~= length(kvaser_variable.time) ...
           || any(group_struct.time.values ~= kvaser_variable.time)
            disp(['Warning: time column of variable ' variable_name ' is different from time column of previously imported ALDW variables'])
        end    
        % Then import the data
        new_variable.values = kvaser_variable.signals.values;
        new_variable.unit = kvaser_variable.unit;
        new_variable.comments = '';
        % update structure
        new_group = getfield(new_struct,group_name);
        new_group = setfield(new_group,variable_name,new_variable);
        new_struct = setfield(new_struct,group_name,new_group);
    else
        % if it doesn't exist, create the timecodes for the
        % ALDW structure
        new_variable.values = kvaser_variable.time;
        new_variable.unit = kvaser_variable.timeunit;
        new_variable.comments = '';
        % update structure
        new_group = struct;
        new_group.time = new_variable;
        new_struct = setfield(new_struct,group_name,new_group);
        % Then import the data
        new_variable.values = kvaser_variable.signals.values;
        new_variable.unit = kvaser_variable.unit;
        new_variable.comments = '';
        % update structure
        new_group = getfield(new_struct,group_name);
        new_group = setfield(new_group,variable_name,new_variable);
        new_struct = setfield(new_struct,group_name,new_group);
    end   
end





