function lanceExport (trip_file)

cellArrayOfMarkersToExport = { ...
%   {'event', 'event_table_name','variable_to_concatenate_to_event_name'}
    {'situation', 'virages', 'nom'},...
    {'event', 'Top', 'Name'},...  
    {'situation', 'commandes', 'type'},...
    {'situation', 'tendance', 'type'},...
    {'situation', 'pedaleEnfonce', 'type'},...
    {'situation', 'gearbox', 'gearbox_position'},...
    {'event', 'Extremum Locaux', 'nom'},...
    };

DataVariableNameForEnrichment = { ...
    {'GPS5Hz.Latitude_5Hz','latitude'},...
    {'GPS5Hz.Longitude_5Hz','longitude'},...
    };

[pathstr, name, ~, ~] = fileparts(trip_file);
csvFile = [pathstr '\trip_' name '4ABSTRACT.csv'];
exportSituationsAndEvents2CSV( trip, csvFile, ';', DataVariableNameForEnrichment, cellArrayOfMarkersToExport);
disp('CSV created for Abstract!  ');

end