function [data] = import_var_ACT3_long(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [TEMPS,VPVOIEMM,VPCAPDEG,VPPKMM,VPVITMS,VPCABVOLANT,VPCABACCL,VPCABFREIN,COM3,COM6]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [TEMPS,VPVOIEMM,VPCAPDEG,VPPKMM,VPVITMS,VPCABVOLANT,VPCABACCL,VPCABFREIN,COM3,COM6]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [temps,vpVoiemm,vpCapdeg,vpPkmm,vpVitms,vpcabvolant,vpcabaccl,vpcabfrein,com3,com6]
%   = importfile('23011407.var',2, 29432);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2014/01/28 11:40:11

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%s%*s%*s%*s%s%s%s%s%s%s%s%*s%*s%*s%*s%*s%*s%s%*s%*s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[2,3,4,5,6,7,8]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\.]*)+[\,]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\.]*)*[\,]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers=='.');
                thousandsRegExp = '^\d+?(\.\d{3})*\,{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, '.', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = strrep(numbers, '.', '');
                numbers = strrep(numbers, ',', '.');
                numbers = textscan(numbers, '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [2,3,4,5,6,7,8]);
rawCellColumns = raw(:, [1,9,10]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
temps = rawCellColumns(:, 1);
vpVoiemm = cell2mat(rawNumericColumns(:, 1));
vpCapdeg = cell2mat(rawNumericColumns(:, 2));
vpPkmm = cell2mat(rawNumericColumns(:, 3));
vpVitms = cell2mat(rawNumericColumns(:, 4));
vpcabvolant = cell2mat(rawNumericColumns(:, 5));
vpcabaccl = cell2mat(rawNumericColumns(:, 6));
vpcabfrein = cell2mat(rawNumericColumns(:, 7));
com3 = rawCellColumns(:, 2);
com6 = rawCellColumns(:, 3);

%% Mise en forme de la structure 'data'

data.scenario = com3{1}(strfind(com3{1},'Scenario'):end);

com =cell(length(com3),1);
for i=1:1:length(com3)
    com{i,1} = [com3{i} com6{i}]; 
end    

data.commentaires = com;

data.temps = temps;

data.vp.voie = vpVoiemm;
data.vp.cap = vpCapdeg;
data.vp.angleVolant = vpcabvolant*360/7500;%conversion de increment vers °
data.vp.pk= vpPkmm;
data.vp.vitesse= vpVitms;
