function batch_import_Atlas_Route()

%       folder_lists = {
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S001\ALLER',...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S001\RETOUR',...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S002\ALLER', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S002\RETOUR', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S003\ALLER', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S003\RETOUR',...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S004\ALLER', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S004\RETOUR',...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S005\ALLER', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S005\RETOUR',...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S006\ALLER', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S006\RETOUR', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S007\ALLER', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S007\RETOUR',...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S008\ALLER', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S008\RETOUR', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S009\ALLER', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S009\RETOUR', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S010\ALLER', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S010\RETOUR', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S012\ALLER', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S012\RETOUR', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S013\ALLER', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S013\RETOUR' ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S014\ALLER', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S014\RETOUR',...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S015\ALLER', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S015\RETOUR', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S016\ALLER', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S016\RETOUR', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S017\ALLER', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S017\RETOUR', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S018\ALLER', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S018\RETOUR', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S019\ALLER', ...
%                      'D:\LESCOT\PROJETS\2013- ATLAS\Atlas Route\DONNEES\MANIPS\S019\RETOUR'};


folder_lists = {'E:\PROJETS ACTUELS\ATLAS\Manip Route\DONNEES\MANIPS\S015\ALLER'};

%     log_csv = fopen('log_import_atlas.csv', 'a+');
%     log_write(log_csv, 'Dossier', 'Mopad2Struct', 'Kvaser2Struct', 'SynchroMopad', 'SynchroKvaser', 'StructMopad2BIND', 'Time Mopad2BIND','StructKvaser2BIND', 'Time Kvaser2BIND');
    
    % On boucle sur les TRIPS
    for i = 1:length(folder_lists)
        full_directory = folder_lists{i};
        REG =regexp(full_directory,'\\');
        participant_name =[full_directory((REG(end-1)+1 : REG(end)-1)) '_' full_directory(REG(end)+1 :end)];
        trip_name= [participant_name '.trip'];
        
        disp(['Processing trip : ' trip_name ' ...' ])
        
        trip_file = [full_directory filesep trip_name];
        
        % open the trip (create the trip if it doesn't exist)
        trip = fr.lescot.bind.kernel.implementation.SQLiteTrip(trip_file, 0.04, true);
        
        %% syncho et création du trip
         %[proc_mopad2struct,    ~, ~]    = magic_process('atlas_mopad2struct',trip,full_directory,participant_name);
         %[proc_kvaser2struct,  ~, ~]  = magic_process('atlas_kvaser2struct',trip,full_directory,participant_name);
        
        %% Kvaser
        
         %[proc_syncMopad, ~, ~] = magic_process('atlas_sync_mopad_video',trip,full_directory,participant_name,'3brakes');
         %[proc_syncKvaser,  ~, ~]  = magic_process('atlas_sync_kvaser_mopad',trip,full_directory,participant_name,'3brakes');
        
        %% MP150
         %[proc_MP150_2struct,    ~, ~]    = magic_process('atlas_MP150_2struct',trip,full_directory,participant_name);
         %[proc_syncMP150,    ~, ~]    = magic_process('atlas_sync_MP150_2mopad',trip,full_directory,participant_name,'3brakes');

%         try
%         visu_synchro(full_directory,'struct');
%         hgsave(['visu_synchro_' participant_name '_struct']);
%         close all
%         catch
%         end
               
        %% IMPORT TRIP
       [proc_import_mopad,  time_import_mopad, ~]  = magic_process('atlas_import_mopad2bind',trip,full_directory,participant_name);
       [proc_import_kvaser_1,  time_import_kvaser_1, ~]  = magic_process('atlas_import_partiel_kvaser2bind_1',trip,full_directory,participant_name);
%       [proc_import_kvaser,  time_import_kvaser, ~]  = magic_process('atlas_import_kvaser2bind',trip,full_directory,participant_name); 
%       [proc_syncMP150,    ~, ~]    = magic_process('atlas_import_MP150_2bind',trip,full_directory,participant_name); 

% try
%          visu_synchro(full_directory,'trip');
%         hgsave(['visu_synchro_' participant_name '_trip']);
%          close all
% catch
% end

        delete(trip)
        
        %% Creation des tracés KML à partir des données brutes
        %Trace_GPS(full_directory)
        
        %log_write(log_csv, full_directory, proc_mopad2struct, proc_kvaser2struct, proc_syncMopad, ...
        %           proc_syncKvaser, proc_import_mopad, time_import_mopad, proc_import_kvaser_1, time_import_kvaser_1,proc_MP150_2struct,proc_syncMP150);
    end
    %fclose(log_csv);
end

