function batchExportTSV_COCORICO(MAIN_FOLDER)
%TODO : uigetdir -> MAIN_FOLDER et uiget pour le case
MAIN_FOLDER = '\\vrlescot.ifsttar.fr\DKLESCOT\PROJETS ACTUELS\THESE_FRANCK\COCORICO\DONNEES_PARTICIPANTS';
EXPORT_FOLDER = [MAIN_FOLDER filesep 'FICHIERS_EXPORT' filesep 'Tableaux_données'];
trip_files = dirrec(MAIN_FOLDER, '.trip');
%% CONSTRUCTION HEADER

HEADER_BASEXP_SCENARIO = ...
    {'id_participant', 'id_groupe', 'id_scenario', 'date', 'heure', ...
    'duree_scenario', ...
    'nb_ech__scenario', ...
    'freq__scenario', ...
    'TIV_moy_scenario', ...
    'TIV_var_scenario', ...
    'vit_moy_scenario', ...
    'vit_var_scenario', ...
    'accel_moy_scenario', ...
    'decel_moy_scenario', ...
    'nb_aCoups_scenario', ...
    'frein_moy_scenario',  ...
    'frein_max_scenario', ...
    'posLatG_moy_scenario', ...
    'posLatD_moy_scenario', ...
    'lat_var_scenario', ...
    'nb_SV_scenario', ...
    'dureeSV_moy_scenario', ...
    'nbFix_scenario', ...
    'dFTot_scenario', ...
    'dFMoy_scenario', ...
    };

HEADER_BASEXP_SUIVI = ...
    {'id_participant', 'id_groupe', 'id_scenario', 'date', 'heure', ...
    'duree_suivi1', 'duree_suivi2', ...
    'nb_ech_suivi1', 'nb_ech_suivi2', ...
    'freq_suivi1', 'freq_suivi2', ...
    'perfCoh_suivi1', 'perfCoh_suivi2', ...
    'perfPhase_suivi1', 'perfPhase_suivi2', ...
    'perfGain_suivi1', 'perfGain_suivi2', ...
    'TIV_moy_suivi1', 'TIV_moy_suivi2', ...
    'TIV_var_suivi1', 'TIV_var_suivi2', ...
    'DIV_moy_suivi1', 'DIV_moy_suivi2', ...
    'vit_moy_suivi1', 'vit_moy_suivi2', ...
    'vit_var_suivi1', 'vit_var_suivi2', ...
    'accel_moy_suivi1', 'accel_moy_suivi2', ...
    'decel_moy_suivi1', 'decel_moy_suivi2', ...
    'nb_aCoups_suivi1', 'nb_aCoups_suivi2', ...
    'frein_moy_suivi1', 'frein_moy_suivi2', ...
    'frein_max_suivi1', 'frein_max_suivi2', ...
    'posLatG_moy_suivi1', 'posLatG_moy_suivi2', ...
    'posLatD_moy_suivi1', 'posLatD_moy_suivi2', ...
    'lat_var_suivi1', 'lat_var_suivi2', ...
    'nb_SV_suivi1', 'nb_SV_suivi2', ...
    'dureeSV_moy_suivi1', 'dureeSV_moy_suivi2', ...
    'nbFix_suivi1', 'nbFix_suivi2', ...
    'dFTot_suivi1', 'dFTot_suivi2', ...
    'dFMoy_suivi1', 'dFMoy_suivi2', ...
    'nbEch_Left_suivi1', 'nbEch_Left_suivi2', ...
    'nbEch_Center_suivi1', 'nbEch_Center_suivi2', ...
    'nbEch_Right_suivi1', 'nbEch_Right_suivi2', ...
    'dureeEch_Left_suivi1', 'dureeEch_Left_suivi2', ...
    'dureeEch_Center_suivi1', 'dureeEch_Center_suivi2', ...
    'dureeEch_Right_suivi1', 'dureeEch_Right_suivi2', ...
    'nbFix_Left_suivi1', 'nbFix_Left_suivi2', ...
    'nbFix_Center_suivi1', 'nbFix_Center_suivi2', ...
    'nbFix_Right_suivi1', 'nbFix_Right_suivi2', ...
    'dureeFix_Left_suivi1', 'dureeFix_Left_suivi2', ...
    'dureeFix_Center_suivi1', 'dureeFix_Center_suivi2', ...
    'dureeFix_Right_suivi1', 'dureeFix_Right_suivi2', ...
    };

HEADER_BASEXP_PIETON = ...
    {'id_participant', 'id_groupe', 'id_scenario', 'date', 'heure', ...
    'tcD_P01', 'tcD_P02', 'tcD_P03', 'tcD_P04', 'tcD_P05', 'tcD_P06', 'tcD_P07', 'tcD_P08', 'tcD_P09', 'tcD_P10', 'tcD_P11', 'tcD_P12', ...
    'tD_P01', 'tD_P02', 'tD_P03', 'tD_P04', 'tD_P05', 'tD_P06', 'tD_P07', 'tD_P08', 'tD_P09', 'tD_P10', 'tD_P11', 'tD_P12', ...
    'distD_P01', 'distD_P02', 'distD_P03', 'distD_P04', 'distD_P05', 'distD_P06', 'distD_P07', 'distD_P08', 'distD_P09', 'distD_P10', 'distD_P11', 'distD_P12', ...
    'vitVpD_P01', 'vitVpD_P02', 'vitVpD_P03', 'vitVpD_P04', 'vitVpD_P05', 'vitVpD_P06', 'vitVpD_P07', 'vitVpD_P08', 'vitVpD_P09', 'vitVpD_P10', 'vitVpD_P11', 'vitVpD_P12', ...
    'tAtt_P01', 'tAtt_P02', 'tAtt_P03', 'tAtt_P04', 'tAtt_P05', 'tAtt_P06', 'tAtt_P07', 'tAtt_P08', 'tAtt_P09', 'tAtt_P10', 'tAtt_P11', 'tAtt_P12', ...
    'nbV_P01', 'nbV_P02', 'nbV_P03', 'nbV_P04', 'nbV_P05', 'nbV_P06', 'nbV_P07', 'nbV_P08', 'nbV_P09', 'nbV_P10', 'nbV_P11', 'nbV_P12', ...
    't1stV_P01', 't1stV_P02', 't1stV_P03', 't1stV_P04', 't1stV_P05', 't1stV_P06', 't1stV_P07', 't1stV_P08', 't1stV_P09', 't1stV_P10', 't1stV_P11', 't1stV_P12', ...
    'dVTot_P01', 'dVTot_P02', 'dVTot_P03', 'dVTot_P04', 'dVTot_P05', 'dVTot_P06', 'dVTot_P07', 'dVTot_P08', 'dVTot_P09', 'dVTot_P10', 'dVTot_P11', 'dVTot_P12', ...
    'dVMoy_P01', 'dVMoy_P02', 'dVMoy_P03', 'dVMoy_P04', 'dVMoy_P05', 'dVMoy_P06', 'dVMoy_P07', 'dVMoy_P08', 'dVMoy_P09', 'dVMoy_P10', 'dVMoy_P11', 'dVMoy_P12', ...
    'nbFix_P01', 'nbFix_P02', 'nbFix_P03', 'nbFix_P04', 'nbFix_P05', 'nbFix_P06', 'nbFix_P07', 'nbFix_P08', 'nbFix_P09', 'nbFix_P10', 'nbFix_P11', 'nbFix_P12', ...
    'dFTot_P01', 'dFTot_P02', 'dFTot_P03', 'dFTot_P04', 'dFTot_P05', 'dFTot_P06', 'dFTot_P07', 'dFTot_P08', 'dFTot_P09', 'dFTot_P10', 'dFTot_P11', 'dFTot_P12', ...
    'dFMoy_P01', 'dFMoy_P02', 'dFMoy_P03', 'dFMoy_P04', 'dFMoy_P05', 'dFMoy_P06', 'dFMoy_P07', 'dFMoy_P08', 'dFMoy_P09', 'dFMoy_P10', 'dFMoy_P11', 'dFMoy_P12', ...
    'nbFix_AOI_P01', 'nbFix_AOI_P02', 'nbFix_AOI_P03', 'nbFix_AOI_P04', 'nbFix_AOI_P05', 'nbFix_AOI_P06', 'nbFix_AOI_P07', 'nbFix_AOI_P08', 'nbFix_AOI_P09', 'nbFix_AOI_P10', 'nbFix_AOI_P11', 'nbFix_AOI_P12', ...
    'dFTot_AOI_P01', 'dFTot_AOI_P02', 'dFTot_AOI_P03', 'dFTot_AOI_P04', 'dFTot_AOI_P05', 'dFTot_AOI_P06', 'dFTot_AOI_P07', 'dFTot_AOI_P08', 'dFTot_AOI_P09', 'dFTot_AOI_P10', 'dFTot_AOI_P11', 'dFTot_AOI_P12', ...
    'dFMoy_AOI_P01', 'dFMoy_AOI_P02', 'dFMoy_AOI_P03', 'dFMoy_AOI_P04', 'dFMoy_AOI_P05', 'dFMoy_AOI_P06', 'dFMoy_AOI_P07', 'dFMoy_AOI_P08', 'dFMoy_AOI_P09', 'dFMoy_AOI_P10', 'dFMoy_AOI_P11', 'dFMoy_AOI_P12', ...
    };

%     'td_vneutre_1', ...
%     'td_vneutre_2', ...
%     'td_vneutre_3', ...
%     'td_vneutre_4', ...
%     'td_vcolere_1', ...
%     'td_vcolere_2', ...
%     'td_vcolere_3', ...
%     'td_vcolere_4', ...

%HEADER_IND_SC = {'idParticipant'};
%HEADER_IND_SL = {'idParticipant'};

file_id_scenario = fopen([EXPORT_FOLDER filesep 'BASEXP_SCENARIO_' char(datetime('now','Format','yyMMdd_HHmm')) '.tsv'], 'w');
fprintf(file_id_scenario, '%s\t', HEADER_BASEXP_SCENARIO{:});
fprintf(file_id_scenario, '\n');

file_id_suivi = fopen([EXPORT_FOLDER filesep 'BASEXP_SUIVI_' char(datetime('now','Format','yyMMdd_HHmm')) '.tsv'], 'w');
fprintf(file_id_suivi, '%s\t', HEADER_BASEXP_SUIVI{:});
fprintf(file_id_suivi, '\n');

file_id_pieton = fopen([EXPORT_FOLDER filesep 'BASEXP_PIETON_' char(datetime('now','Format','yyMMdd_HHmm')) '.tsv'], 'w');
fprintf(file_id_pieton, '%s\t', HEADER_BASEXP_PIETON{:});
fprintf(file_id_pieton, '\n');

for i_trip = 1:length(trip_files)
    trip_file = trip_files{i_trip};
    trip = fr.lescot.bind.kernel.implementation.SQLiteTrip(trip_file, 0.04, false);
    
    if check_trip_meta(trip, 'id_scenario', 'BASELINE') || check_trip_meta(trip, 'id_scenario', 'EXPERIMENTAL')
        
        if trip.getMetaInformations().existSituation('scenario_complet')
            disp(['exporting : ' trip_file])
            exportTripSituation2TSVByParticipant_COCORICO(trip_file, file_id_scenario, 'scenario_complet')
        end
        
        if trip.getMetaInformations().existSituation('suivi_cible')
            disp(['exporting : ' trip_file])
            exportTripSituation2TSVByParticipant_COCORICO(trip_file, file_id_suivi, 'suivi_cible')
        end
        
        if trip.getMetaInformations().existSituation('pieton')
            disp(['exporting : ' trip_file])
            exportTripSituation2TSVByParticipant_COCORICO(trip_file, file_id_pieton, 'pieton')
        end
        
    elseif check_trip_meta(trip, 'id_scenario', 'INDUCTION')
        
        %         if trip.getMetaInformations().existSituation('section_libre')
        %             exportTripSituation2TSVByParticipant(trip_file, file_id_SL, 'section_libre')
        %         end
        %
        %         if trip.getMetaInformations().existSituation('section_contrainte')
        %             exportTripSituation2TSVByParticipant(trip_file, file_id_SC, 'section_contrainte')
        %         end
        
    end
    delete(trip);
end
fclose(file_id_suivi);
fclose(file_id_pieton);
disp([num2str(length(trip_files)) ' trips exportés.'])
end

function buildHeader(situation_id)
situation_variable_names = trip.getMetaInformations().getSituationVariablesNamesList(situation_id);


end