function [methodinfo,structs,enuminfo,ThunkLibName]=DShowAudio4BINDheader
%DSHOWAUDIO4BINDHEADER Create structures to define interfaces found in 'DshowAudio4BIND'.

%This function was generated by loadlibrary.m parser version 1.1.6.32 on Wed Aug 11 10:32:51 2010
%perl options:'DshowAudio4BIND.i -outfile=DshowAudio4BINDheader.m'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival);
ThunkLibName=[];
% extern " C "  int LoadAudio ( char * audiofile ); 
fcns.name{fcnNum}='LoadAudio'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring'};fcnNum=fcnNum+1;
% extern " C "  void Play ( int audio_id ); 
fcns.name{fcnNum}='Play'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'int32'};fcnNum=fcnNum+1;
% extern " C "  void Pause ( int audio_id ); 
fcns.name{fcnNum}='Pause'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'int32'};fcnNum=fcnNum+1;
% extern " C "  void SetPosition ( int audio_id , long long position ); 
fcns.name{fcnNum}='SetPosition'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'int32', 'int64'};fcnNum=fcnNum+1;
% extern " C "  void UnloadAudio ( int audio_id ); 
fcns.name{fcnNum}='UnloadAudio'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'int32'};fcnNum=fcnNum+1;
% extern " C "  bool NoMoreAudio (); 
fcns.name{fcnNum}='NoMoreAudio'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='bool'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
% extern " C "  void SetRate ( int audio_id , double rate ); 
fcns.name{fcnNum}='SetRate'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'int32', 'double'};fcnNum=fcnNum+1;
methodinfo=fcns;